baseURL = "https://docs.omnius-labs.com/"
languageCode = "en-us"
title = "Omnius Labs"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/omnius-labs/docs/tree/master/content/"
author = "Lyrise"
themeVariant = "black"

[Languages]

[Languages.en]
title = "Omnius Labs"
weight = 1
languageName = "English"
