site_name: Omnius Labs
theme:
    name: 'material'
pages:
- Home: 'index.md'
- Projects: 
    - Omnix:
        - 'Home': 'omnix/index.md'
    - Xeus:
        - 'Home': 'xeus/index.md'
    - Lxna:
        - 'Home': 'lxna/index.md'
